### PR TITLE
Fixed error for Convertion from palo to checkpoint.

### PR DESCRIPTION
**Pull request by mymyke**
Wrong variable was used. policy_src_address instead of policy_source_address

### CODE REVIEW

**Comment by VahidTa** [comment]
First of all thanks for your contribution to this project.
Additionally, the codebase is not well structured as it is almost my first Python project. 

please attach the input/output file and the version you have tested. (before your change and after)

**Review by VahidTa — CHANGES_REQUESTED** [review]
Please remove the input/output files from the PR. Thanks for sharing. My point was to attach the input/output files to comments.

**Comment by mymyke** [comment]
Oh my bad. 
Removed the input/output files again and adding them to this comment


[palo-config-test.txt](https://github.com/user-attachments/files/16044470/palo-config-test.txt)
[service-tcp.csv](https://github.com/user-attachments/files/16044473/service-tcp.csv)
[service_groups.csv](https://github.com/user-attachments/files/16044474/service_groups.csv)
[service_groups_members.csv](https://github.com/user-attachments/files/16044475/service_groups_members.csv)
[policies.txt](https://github.com/user-attachments/files/16044476/policies.txt)
[network_objects_network.csv](https://github.com/user-attachments/files/16044477/network_objects_network.csv)
[network_objects_host.csv](https://github.com/user-attachments/files/16044478/network_objects_host.csv)
[network_groups.csv](https://github.com/user-attachments/files/16044480/network_groups.csv)
[network_group_members.csv](https://github.com/user-attachments/files/16044481/network_group_members.csv)

**Comment by VahidTa** [comment]
put back `.keep` file under "exported"

**Comment by VahidTa** [comment]
Please remove the ".keep" file under the "exported" directory. Otherwise, I can't merge it and I'll close the MR

**Comment by mymyke** [comment]
I put back .keep file under "exported". Hope that helps

**Review by VahidTa — APPROVED** [review]

**Pull request merged**
